### ISSUE TITLE
Property counting the total number of self loops?

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#106]

**Comment by Yomguithereal** [comment]
What about `#.selfLoops` and `#.directedSelfLoops` and such. But collision with the `#.selfLoop` method?

**Comment by jacomyal** [comment]
If I see `#.selfLoops` close to `#.edges`, I will suppose both things work the same way, since the naming is so similar. What do you think about something like `#.selfLoopsCount` instead?
