### ISSUE TITLE
Use graphology with (declarative) rendering using svg/React ? 

### ISSUE THREAD

**Issue by clemsos** [graphology/graphology#109]
Hello, 

I would like to know how to use graphology to visualize graphs using React or d3 to parse SVG. Is there existing examples of graphology+react or grapholgy+d3 graph?

**Comment by Yomguithereal** [comment]
If you need to visualize graphs dynamically, you can use sigma v2 (check the [examples](https://github.com/jacomyal/sigma.js/blob/v2/examples/basic.js) here). But it's still a very early alpha and only supports a WebGL renderer to display very large graphs.

Shouldn't be too hard however to plug a graphology graph into d3 also but I don't have a ready example to show you.

If what you need is just to render a static SVG, I intend to create a `graphology-svg` lib in the like of the `graphology-gexf`one in a near future and you can help me design it if you want.

Else you can check some of the scripts rendering a graph into SVG in the [graph-recipes](http://tools.medialab.sciences-po.fr/graph-recipes/) tool.

**Comment by Yomguithereal** [comment]
On a side note, if you need to render you graph as static SVG, using react to do so might be a fun option.

**Comment by clemsos** [comment]
Thanks for the heads up. I am relying mostly on react for my application so I am going to try how it can fit with larger number of nodes. 

Here is a basic test based on sigma.js example https://gist.github.com/clemsos/1a77e4257b2c97abaf79d73dcdab08ec

**Comment by clemsos** [comment]
![screenshot-localhost-8000-2017-10-19-20-26-26-372](https://user-images.githubusercontent.com/743246/31787365-d314e272-b50b-11e7-94d0-1bfbe1782d5c.png)

**Comment by clemsos** [comment]
Just made a basic React component to be used with graphology https://github.com/clemsos/graphology-react

**Comment by Yomguithereal** [comment]
That's a very good start. However, will you need it to be dynamic one day? Like with a camera or so on? This approach works very well to render static SVG but declarative rendering will only get you so far if you need performance.

**Comment by clemsos** [comment]
I did not think about it, but yes a camera can be interesting indeed. The declarative approach is useful as I dont plan to have only a network viz. If the nodes are plain SVG, I can sort/reorganize them however I wish and I don't need to rewrite things like mouse interactions, etc.

For larger graphs and eventual camera support, one possibility will be canvas rendering - with [Konva](https://konvajs.github.io/) for instance.

**Comment by Yomguithereal** [comment]
If you need large graph, you should try the sigma examples I showed you. They use WebGL and will scale way beyond canvas?

**Comment by clemsos** [comment]
Yep, sigma is great. My concern is that I am trying to visualize networks that changes very fast. It doesn't have to be large networks for now, but the structure and data are changing fast so I need to be able to push and reflect changes easily. 

The problem with libs like Sigma or Cytoscape is that they are basically models with a renderer, so I will have to diff the data first to see what has changed, then update the rendering with methods like `addNode`, `deleteNode` and the like - which 1) add complexity to the code and 2) affect performance big time. That is why I am looking for sth more declarative / reactive - like React - so it does all the diff when new data is passed. As graphology is just the model with features, it would be great for me to just plug a reactive renderer that does not have a model by itself. 

Not sure if what I say make any sense... There may be a more clever approach but I cant think of any right now.

**Comment by Yomguithereal** [comment]
I see your point. But the fact is that sigma & cytoscape do not follow the imperative or model/renderer paradigm for pleasure but because it is the only way to remain as performant as possible.

> so I will have to diff the data first to see what has changed

Basically, react will do the same thing for you and will diff the DOM (and thus the underlying data) to be able to render your graph.

One middle way consist in creating components able to react to the graph's update in another way than through the props etc. by meshing both imperative & declarative methods but it has limits and is quite tedious to code.

**Comment by clemsos** [comment]
Thanks for the explanation, very helpful. The mixed-approach you described is what I am currently using in the [network app I am developing](https://github.com/topogram/topogram/blob/f4255661e3b6eae42b9a14668cb3e8f1d66fe813/imports/client/ui/components/network/Network.jsx#L157).

I will continue to explore the current approach with graphology and props, and let React to the diffing. Just to see how far I can go with that. One thing I want is to be able to use nodes as dots, and position them according to whatever order/positions I like (bar graphs, drawings, geo projections, etc). I tried with cytoscape but it is very hard to map x/y. With d3 it will be possible but then I will lose all the native functions for network manipulations (neighborhood, paths, etc). 

Anyway, need some more exploration and testing to understand what I am doing :smile: 

Thanks again!
