### ISSUE TITLE
consider immer for immutability 

### ISSUE THREAD

**Issue by matt-erhart** [graphology/graphology#123]
Since it (https://github.com/mweststrate/immer) uses mutations wrapped in function and has structural sharing and all that, could be a good way to support immutability in those situations where we want to, e.g. rerender after any change to the graph.

**Comment by Yomguithereal** [comment]
Hello @matt-erhart. This could be an option indeed even if for this particular use case I'd wager that [immutable-js](https://facebook.github.io/immutable-js/) would be more performant. On a side note, if you render large graph using dedicated rendering engines (such as d3 or sigma) you cannot afford immutability and will need to rely on something else than referential equality to be able to know when/what to render. Do you have a particular use case in mind?

**Comment by matt-erhart** [comment]
Cool, use case is basically using a graph as a react component state, which is immutable. There's some perf comparisons on the immer site. The slatejs editor folks started with immutable but the weird api ended up being a pain for users and they're thinking of switching to immer. On big graphs, I've gone for not-react too. For react, I guess this is mainly a mid-range 100ish nodes situation. Anyhoo, just thought I'd throw that out there. Cool lib!

**Comment by Yomguithereal** [comment]
> Cool, use case is basically using a graph as a react component state, which is immutable.

Interesting. Can I see the code or an example somewhere? Are you representing a graph in memory? Is your data shaped likewise? Is this something completely different?

**Comment by acnebs** [comment]
Sorry to resurrect a dead issue @Yomguithereal, but I'm actually also trying to figure out how I can possibly use Graphology for state management alongside React. Basically I have graph data that I'd like to display in different ways: as a collapsible tree view, as a 2d graph (sigma), or just as a list of items matching certain criteria.

I can imperatively interact with a graphology `Graph` for this purpose, e.g. when any one of those views / components loads I can make a call against the graph object and get the data I need. But obviously I actually want this to be declarative, where I specify which parts of the graph I need for a certain component, and if the *relevant* part of the graph changes, that component will re-render.

Any thoughts?
