### ISSUE TITLE
addNodesFrom is not a function

### ISSUE THREAD

**Issue by matt-erhart** [graphology/graphology#124]
Looks like the addNodesFrom  function was removed and the first example in the intro needs an update.

**Comment by Yomguithereal** [comment]
You are right. However I thought I removed every link to those examples. Did you find them by perusing the docs' sources?

**Comment by matt-erhart** [comment]
Sorry too vague, it's in https://graphology.github.io/instantiation.html#static-from-method in the 'Edge key generator function' example.

**Comment by Yomguithereal** [comment]
Thanks. I'll edit the examples as soon as possible.

**Comment by Yomguithereal** [comment]
The examples were edited to keep a single `#.mergeEdge` call. I'll close this then. Thanks @matt-erhart for the heads up.

**Comment by Jacse** [comment]
There are also references to said function under [concepts](https://graphology.github.io/concepts.html).

**Comment by Jacse** [comment]
They are also still in [tests](https://github.com/graphology/graphology/search?p=2&q=addNodesFrom&unscoped_q=addNodesFrom)

**Comment by Yomguithereal** [comment]
Thanks for noticing this @Jacse. Would you have some time to file a PR to fix those examples?

**Comment by redexp** [comment]
There are still many places with this method
https://github.com/search?q=repo%3Agraphology%2Fgraphology+addNodesFrom+language%3AMarkdown&type=code&l=Markdown

**Comment by Yomguithereal** [comment]
Thanks @redexp they are now gone.
