### ISSUE TITLE
Implement graph query language support like Cypher or Gremlin

### ISSUE THREAD

**Issue by NtsDK** [graphology/graphology#127]
I want to use graph database in my javascript project but I don't find any embeddable JS Graph DB which use standard widespread graph query language like Cypher or Gremlin.
I think such tool will be very valuable.

**Comment by Yomguithereal** [comment]
Hello @NtsDK. While this is a cool idea, this would require a lot of time to develop something like Cypher or Gremlin integration. My guess is that a superclass of graphology featuring indices on node labels and edge types would be a first step towards what you need, what do you think? Do you want to describe your use case a bit more?

**Comment by NtsDK** [comment]
Hello @Yomguithereal ! 

I understand this is a big project but maybe I'm not alone interested in this idea. I think the superclass idea is a good start point.

So about my project. 

1. My opensource project needs rich datastructure. Principally this is a domain specific text editor. It has entities of several types with complex relations. It works in browser both as text editor and visualize system.
2. One of the major concept - it should work both offline and online. I made two versions. One is a static webpage which works offline. And second is a node express server. Both use the same JS data engine.

What I expect from data engine?

- Abstraction - is it a good idea behind engine API? Relational algebra and graph algorithms are good. Document-oriented approach is weaker.
- Schema validation - not necessary out-of-the-box but this is important.
- Flexibility - simple schema changing. Documents and graphs are good in this.
- Performance - it should be good enough. It is not highload with server manycores and RAM terabytes. But it should work in single thread browser and MAAYBE SOMETIME in tablet app or browser.
- Easy to manage data dump. I don't do it often but this improves developer experience.
- Relation support is very important. Graph databases are the best in this area.
- Projection of data domain on database structure. I think this is the biggest problem of SQL DBMSes. It is very unnatural for many data domains but it is solid and fast.

Right now I store data in a big JSON object. 

- Good: Schema, Flexibility, Dumps
- Bad: Abstraction, Relations
- SoSo: Database structure

The problem - relation support is not automated. Adding new data relations increase complexity. No abstraction layer.

My graph DB expectations.

- Good: Abstraction, Relations, Database structure, Flexibility
- I don't know what happens with other properties in graph case.

Also interesting question: should be data engine API sync or async?
For me sync API will be more preferable. It is like naive transaction support but maybe this concept has flaws.

Ask me if you have more questions.

**Comment by av8ta** [comment]
I too would love to have a query language to use with graphology. Have you seen this new project? https://github.com/kristianmandrup/cypher-query

**Comment by sim51** [comment]
FYI, I started a gremlin implementation on top of graphology here https://github.com/sim51/graphology-gremlin
But it's still in WIP. I need to found time to work again on it

**Comment by av8ta** [comment]
Looks like you're [making good progress](https://github.com/sim51/graphology-gremlin/blob/main/test/index.ts) @sim51 ! Happy to cheer you on and contribute too. I'm new to this field though!

**Comment by sim51** [comment]
Yep, but from what I remember I need to : 
 * review some types on typescripts 
 * find a way to apply where predicates with  good TS support 
 * * making docs :D

**Comment by av8ta** [comment]
Please keep going. It looks great.
