### ISSUE TITLE
Adding the #.incident(edge, node) method

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#134]
@jacomyal needs a method to tell whether an edge is incident to a given node. Something like:

```js
graph.incident(edge, node);
```

Is the name correct? Is the argument order correct?

**Comment by Yomguithereal** [comment]
@sim51 what do you think?

**Comment by sim51** [comment]
`incident` is bad for me : 
  - multi meanings in spoken language 
  - incident in graph can be applied to two edges, not only between a node and a edge

I prefer `hasExtremity(edge, node)`
