### ISSUE TITLE
Self loops do not appear in #.inEdges nor in #.inNeighbors

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#140]
They appear in outEdges though. This looks like a bug. Even if this is convenient.

```js
var g = new DirectedGraph();
g.mergeEdge(1, 1);

g.inEdges(1).length
>>> 0

g.outEdges(1).length
>>> 1
```

We will also need to check `inboundEdges` to be sure they are included.

We also have the same issue with neighbors.

**Comment by Yomguithereal** [comment]
@sim51 @jacomyal what's your take on this? Do we agree that the self-loop should appear in both?

**Comment by sim51** [comment]
Yes !
