### ISSUE TITLE
Loosen plain object tests

### ISSUE THREAD

**Issue by jgg3** [graphology/graphology#149]
I am seeing an issue in Node 12, where addNode is failing because I pass an object literal as the second argument.

`const node = graph.addNode("n1", {data: 4});`
Results in an "Graph.addNode: invalid attributes. Expecting an object but ..."

Some digging points to this in isPlainObject:
`value.constructor === Object` returning false.

I searched and can't find any mention of this.  Has something changed here?  Even some examples show the object literal syntax.

**Comment by jgg3** [comment]
This was found to be a problem in the online testing environment.  So, closing.

**Comment by Yomguithereal** [comment]
This is weird indeed. I cannot reproduce your bug either. Does your testing env rely on web workers somehow?

**Comment by jgg3** [comment]
Thanks for your attention.  I was testing on Repl.it, and it seems to have this issue.  https://www.katacoda.com/courses/nodejs/playground  does not.  So it is something with the node runner.  But once found, I was able to by this problem, and it is no problem in Graphology.

**Comment by blake-newman** [comment]
I believe this can be caused when [`runInNewContext` is used within node](https://nodejs.org/api/vm.html#scriptruninnewcontextcontextobject-options). This can be used to isolate code execution from the global instance in a sandbox like environment.

The `isPlainObject` method does a check for `value.constructor == Object` which is returning false.

I don't have enough understanding why that may be the case (Id assume the Object instance has been sandboxed). 

Changing the implementation to follow this https://github.com/jonschlinkert/is-plain-object, resolves the issue.

I'll submit a PR adjusting the implementation to follow suit - which should resolve this issue for when running in this type of environment. (Which we are currently trying to do and running against this issue)

**Comment by Yomguithereal** [comment]
Hello @blake-newman, I am reading the from `is-plain-object` and it seems to be better indeed than my naive test regarding frames and different contexts of execution. This said, it is less performant also. In my case, I am wondering whether I should somehow drop or relax this condition altogether such as testing `typeof value === 'object'` which is of course very imperfect but should catch some of the most probable runtime errors. In any case people can use TS if they want to mind this issue better. What is your opinion on this?

**Comment by blake-newman** [comment]
I would say loosening is best; the use cases that I can see are very trivial. It would be fairly obvious to user land with the runtime errors that would be exposed is not an object. The users are completely ignoring the expected document API in these situations. TS certainly helps avoid the unexpected runtime behaviour.

**Comment by BarryLuijten** [comment]
Thank you @Yomguithereal! This update certainly solved my issues! 😃
