### ISSUE TITLE
Find all paths vs find shortest path

### ISSUE THREAD

**Issue by acnebs** [graphology/graphology#150]
I haven't seen anything like this in the STL and my graph theory isn't great, but I was wondering if `graphology` allows for an easy way to find *all* paths between two nodes, rather than just finding the shortest path with something like A* or Djikstra.

**Comment by Yomguithereal** [comment]
Hello @acnebs. I haven't implemented a `allShortestPath` yet but you can just apply the `singleSource` of unweighted or dijstra `graphology-shortest-path` [here](https://github.com/graphology/graphology-shortest-path/#singlesource) on all of your nodes and get the same result. You could do it faster using Brandes' optimization and such but this operation is quite costly anyway.

**Comment by Yomguithereal** [comment]
Oh, sorry, I misread your issue. You want all paths between two given nodes, fair enough. I don't have this in store as I suspect it might be `O(n!)` or something of the kind. But if you can point me towards an implementation somewhere we can discuss adding this to `graphology-shortest-path`.

**Comment by acnebs** [comment]
Yep, the latter. I have data that is a directed graph, which I want to display as a tree. When the user opens one of the items in the graph, I want to be able to "expand" the tree to show every place in the tree where that node is.

My best idea for doing this was to have all of the cards without a parent (e.g. root nodes) be children to an imaginary root node. Then when I want to expand the tree automatically, I just find all paths between the selected node and the root node, and apply an "open" attribute to all the nodes inbetween.

**Comment by Yomguithereal** [comment]
> Yep, the latter. I have data that is a directed graph, which I want to display as a tree. When the user selects one of the items in the graph, I want to be able to "expand" the tree to show every place in the tree where that node is.

Can I ask you what is the end goal here? It looks like visualizing betweenness centrality in a way.

I guess, but this is costly, you could compute all the shortest paths between each node and all others using `singleSource`beforehand and filter through the paths you have including your selected node.


Okay so, if I understand correctly

**Comment by acnebs** [comment]
Well this is just part of the UI (a tree view of the user's data) so that the user can easily navigate between items. But the user doesn't need to use the tree to navigate, so when they get to an item in any way, we want to show them where in the tree that item is located to help them understand its context.

**Comment by Yomguithereal** [comment]
Okay but do you display a single tree? Or one tree per node, or leaf or root? In both cases you can perform a bfs/topological sort from the targeted node to build the trees but their shape will be kinda arbitrary anyway.

**Comment by acnebs** [comment]
An illustration might help! Let's say I have this graph:

<img width="300" alt="Screen Shot 2020-07-09 at 2 27 36 PM" src="https://user-images.githubusercontent.com/9054108/87046070-96879080-c1f0-11ea-9feb-7fb3fd881bb8.png">

I would then have this tree
- 0
  - 1
    - 6
    - 9
  - 5
    - 8
- 2
  - 3
    - 6
    - 7
    - 8
  - 4
    - 9
    - 10
  - 5
    - 8
  - 10

Which is initially collapsed, so you only see `0` and `2`. When someone selects an item, (let's say `9`), I want to expand all the intermediary nodes to "reveal" the selected node.

**Comment by Yomguithereal** [comment]
Ok I see now. Am I correct to assume that your graphs are always acyclical?

**Comment by acnebs** [comment]
Actually they can be cyclical, but when displaying as a tree we only show one cycle.

**Comment by Yomguithereal** [comment]
Ok, so would a DFS following links in reverse work for you in that case?

**Comment by acnebs** [comment]
Yep, that sounds about right.

Though talking about cyclicality is making me wonder about other facets of this hahaha. The goal of using `graphology` is to simplify management of this data so that I can display it as a graph or as a tree or whatever and perform graph operations on it going forward with only one underlying representation. Though with how the tree is currently implemented, it would be hard to short-circuit the infinite recursing of a cyclical graph.

**Comment by Yomguithereal** [comment]
> Though with how the tree is currently implemented, it would be hard to short-circuit the infinite recursing of a cyclical graph (the prevention of this is currently happening at the data layer, which I intended to replace with graphology).

Infinite recursion related to cycles is always implemented using a set of already visited nodes for graphs. There is no real way around this apart in some very specific cases. A BFS for instance is often implemented [likewise](https://github.com/graphology/graphology-shortest-path/blob/master/unweighted.js#L215-L245).

What I am wondering know is how I can help you, on the graphology side of things?

**Comment by acnebs** [comment]
Well either way I'm going to being using `graphology` in conjunction with v2 of [sigma](https://github.com/jacomyal/sigma.js) for actual display of the graph as a graph. I was hoping it would be easy to use `graphology` as the backend for the tree view in a similar way, but it probably makes more sense to actually implement something before I clutter up GH issues.

I'll close this for now and re-open if/when there is something more actionable to discuss.

Thanks for all your help so far @Yomguithereal!
