### ISSUE TITLE
Add weight to nodes and edges

### ISSUE THREAD

**Issue by Jimmy89** [graphology/graphology#155]
I just started using this library and I want to add a weight to an edge and preferable to a node as well to indicate which connections are better. Example: 0, 1 or 2 as weighted value. However, it looks like this library always assumes 1 as weight for all edges and nodes. Is it possible to provide a weight or otherwise request this feature?

**Comment by Yomguithereal** [comment]
Hello @Jimmy89. You can handle weights simply by storing a node or edge attribute keeping track of it. This library, like `networkx` and many others, does not "sacralize" a way to think about weights etc. because it would be pointless to handle specifically the many many concepts found in graph theory as a whole. So here is an example with edge weights for instance:

```js
graph.addEdge('A', 'B', {weight: 34});

// Incrementing a graph's edge while building it
if (graph.hasEdge('A', 'B'))
  graph.updateEdgeAttribute('A', 'B', 'weight', w => w + 1);
```

Note that all `graphology` libraries assume this is the way you will store weights but also give you a way to specify other attribute names etc.

**Comment by eric-wieser** [comment]
I suspect the question might have been how to associate weights with edges which are then used in the layout algorithm.

**Comment by Yomguithereal** [comment]
Hello @eric-wieser. If this is the case, the answer should then be this one: all of the relevant libraries able to consider weighted edges (such as layouts, some centralities, shortest path etc.) are able to do so using settings provided by the user to indicate 1. if we should consider weights at all (typically a boolean setting called `weighted`) and 2. what is the name of the edge's attributes containing their weights (by convention, it is always `weight` but you can customize the name through the `attributes.weight` setting).

For a real-life example, see the docs of the betweenness centrality [here](https://graphology.github.io/standard-library/metrics.html#betweenness-centrality).

**Comment by Yomguithereal** [comment]
In the special case of the FA2 layout, the setting is called `edgeWeightInfluence` and must be passed as a scaling factor, for historical reasons.

**Comment by eric-wieser** [comment]
Thanks, I worked out what I needed in the end; for a FA2 layout, you set `edgeWeightInfluence` to enable edge weights at all, then you set `weight` as an attribute on the individual edges to assign different weights per edge.

**Comment by Yomguithereal** [comment]
This said, maybe we should harmonize the FA2 layout options and the way the standard lib works in this regard, this would be less confusing (and allow you to specify another name than `weight` if you need to). Also I guess we could accept arbitrary getter functions if you want to store those weights outside of the graph, what do you think?

**Comment by eric-wieser** [comment]
Frankly I'm happy with having to mess around with my graph to make FA2 aware of the weights; all I was missing was documentation telling me it was possible!

**Comment by Yomguithereal** [comment]
Fair enough @eric-wieser :) Do you want to contribute a little addendum to FA2's doc [here](https://github.com/graphology/graphology/tree/master/src/layout-forceatlas2) explaining how you can make it consider edge weights?
