### ISSUE TITLE
Add offset of parallel edge in key generator and events

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#180]

**Comment by Yomguithereal** [comment]
Hello @zszq. I am not sure you are opening your issue at the correct place. `graphology` is just a data structure and does not not render graphs as node-link diagrams. So I guess you are speaking about sigma.js and its v2 does not support drawing parallel edges as bezier curve yet. I think the v1 used to be able to do this but it does not rely on `graphology`.

**Comment by zszq** [comment]
Thank you, I want to know what effect will multi setting true have? And what does allowSelfLoops do?

**Comment by Yomguithereal** [comment]
> Thank you, I want to know what effect will multi setting true have?

What effect on what? If you set `multi` to `true` the underlying data structure will allow multiple edges to be created between any two nodes. This means you can have multiples edges between node `A`  and node `B` for instance, which is not possible in a simple (i.e. not multi) graph.

> And what does allowSelfLoops do?

It allows self loops, i.e. edges from and to the same node, like an edge going from node `A`  to the same node `A`.

**Comment by zszq** [comment]
thanks

**Comment by zszq** [comment]
> > Thank you, I want to know what effect will multi setting true have?
> 
> What effect on what? If you set `multi` to `true` the underlying data structure will allow multiple edges to be created between any two nodes. This means you can have multiples edges between node `A` and node `B` for instance, which is not possible in a simple (i.e. not multi) graph.
> 
> > And what does allowSelfLoops do?
> 
> It allows self loops, i.e. edges from and to the same node, like an edge going from node `A` to the same node `A`.

allows self loops，but using < graph.edges('nodeKey')  > can't get all edges，How to deal with this problem
