### ISSUE TITLE
The magical classical pattern

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#19]
@jacomyal @boogheta @sim51 open question:

What do you think of networkx etc. and their pattern assuming to add everything that wasn't referenced before. What I mean is that, their `#.add_node` is actually our `#.mergeNode` and that any node in an edge extremities absent from the graph is automagically added.

Are our less magical but more explicit and "reasonable" approach better or not?

**Comment by sim51** [comment]
Better for me because you have to explicit what you want to do (a create or a merge).
FYI it's the same in cypher.

**Comment by Yomguithereal** [comment]
If think the root of the problem is that, almost generally, every data structure (let's take an object, a Set or a Map as example), consider the addition of an already added item as a no op. So people just transpose this on graphs. The problem with graphs is that we are handling higher-level data structures which are inherently more complex. We are associating a key to a complex value whose integrity we must ensure. So, keeping the general approach forcefully becomes "magical" à la networkx. Our way is therefore opinionated but, as we all seem to feel, more consistent.

On a side note, cypher does not have the issue of having to create the nodes before linking them and can perform both in the same operation. However, in a typical code API this becomes cumbersome and networkx does not solve the problem in that, yes, missing nodes in a link will be added but you won't be able to give attributes to the nodes in this operation. Cypher is more powerful and you can do so. But being a DSL, the comparison is somewhat unfair :).

**Comment by boogheta** [comment]
I also think having the two options of strict (add) and magical (merge) is better, this way both behaviors are possible and one can do whatever he feels preferable.
