### ISSUE TITLE
Any implementation of Critical-Path-Method Using Graphology?

### ISSUE THREAD

**Issue by flaviotsf** [graphology/graphology#196]
Any open-source implementation of Critical Path Method https://en.wikipedia.org/wiki/Critical_path_method to calculate project durations (modeled as a DAG)?

**Comment by Yomguithereal** [comment]
Hello @flaviotsf. There is no such implementation for graphology yet I think. From afar it looks like longest path search in DAGs. Would you want to contribute such an implementation?
