### ISSUE TITLE
BFS traversal doesn't seem to properly account for undirected edges

### ISSUE THREAD

**Issue by ohxh** [graphology/graphology#197]
Unless I'm misunderstanding the API for adding edges, BFS traversal only seems to look at undirected edges in one direction.

In a decently dense random graph (where we expect a large part to be one connected component), a BFS traversal from a node inside the component doesn't find the entire component. If you double up all the edges in the opposite direction, the value is as expected.

This is a pretty sparse issue, but I imagine for a maintainer of this project this would be a quick fix-- just swap out `forEachOutboundNeighbor` or change its implementation. I'll try to upload a working reproduction later.

**Comment by Yomguithereal** [comment]
Hello @ohxh, I am not sure to follow you. Are you meaning to report an issue regarding the BFS function of [`graphology-traversal`](https://github.com/graphology/graphology-traversal#bfs)?

**Comment by ohxh** [comment]
Ah sorry, forgot about the split packages. I'll post over there. Thanks!
