### ISSUE TITLE
The edge merge conundrum

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#2]
@sim51, can you describe your yesterday's use case so we can assess what to do? As a reference [here](https://graphology.github.io/instantiation.html#duplicate-elements) is how we first addressed the problem.

**Comment by Yomguithereal** [comment]
@sim51 could you also put a link towards Neo4j's Java Graph API doing this kind of merge stuff if this is open sourced please?

**Comment by sim51** [comment]
No prob, I will do it this week-end.

**Comment by Yomguithereal** [comment]
You lied :-)

**Comment by sim51** [comment]
Indeed ... but last week my home door would not opened even with the key ^^

Cypher has a `MERGE` syntax, It can search on the primary key but also make some complex search based on node's properties. To do something similar, you will need query/search langage, so it's a bit overkill for an graph API.

I have a question: what happened if the 'key' passed to the merge function doesn't exist ?  Is the node created or do you throw an exception ?

When you import a file, for example a CSV) you have to transform each row into a graph pattern. If you import this CSV `firstname,lastname,country` and want to transform it into two nodes ( Person and Country), having a merge that can also create nodes is really a good thing (you don't have to store a state of created nodes). Later, you also have to implement the `ON CREATE` & `ON UPDATE` callback.

Cheers.

**Comment by Yomguithereal** [comment]
The merge function, (I assume we speak about `onDuplicateNode` & `onDuplicateEdge` here), will do exactly what you want. It can add nodes, it can just edit attributes etc. It remains to be decided by the developer.

The `ON CREATE` & `ON UPDATE` callback are handled by the events fired by the graph (`nodeAdded` & `nodeUpdated` for instance).

**Comment by Yomguithereal** [comment]
The question also was, is the `onDuplicateNode` etc. option enough to handle the merge use cases or would some method along `mergeNode` or `mergeEdge` be somewhat useful also.

**Comment by Yomguithereal** [comment]
Can we speak sometimes through IRC or Slack or whatever to solve this issue @sim51?

**Comment by sim51** [comment]
Is there a chan on freenode ? I'm avalaible friday evening, this week-end or when you want next week after wednesday.

**Comment by Yomguithereal** [comment]
Ok, after spending it some thoughts, here is what I propose @sim51:

## Behavior of the graph

The default behavior of the graph is to throw whenever someones tries to add an already existing node or edge.

```js
graph.addNode('John');
// Ok, go ahead
graph.addNode('John');
// Throws: already in there, you moron!
```

Deeming a node already exists in the graph is obvious. However, it is less so for an edge so here is the logic followed by the graph:

* In a simple graph, a duplicate edge is either an edge the same source/target combo and the same type (directed or not).
* In a multi graph, a duplicate edge is an edge with the same key.

This basically means that when looping on path lists, notably something along the example you described above, you have to check the existence of said node/edge before adding it to the graph:

```js
// Let's say we have a list of "edges" only:
const list = [
  {country: 'China', name: 'John'},
  {country: 'China', 'Margaret'}
];

// And we iterate over it:
list.forEach(function({country, name}) {
  // I need to check whether the edge exists before attempting to add it:
  if (!graph.hasNode(country)) {
    graph.addNode(country);
  }
  //...
});
```

We both agree that this is somewhat cumbersome.

## Current pieces of solution

Currently the graph accept two options named respectively `onDuplicateNode` & `onDuplicateEdge` and that will fire whenever a duplicate element is inserted in the graph and lets you handle the issue using a function taking the graph instance & the attached data of the element.

This is very useful to create graphs that will treat similar insertions as a weight increment, for instance.

Also, a `addMissingNodes` boolean option is being drafted to be able to automatically add nodes not found in the graph when adding an edge (default case for some library which we decided against as a default to ensure the devs knows what they are doing).

## Proposition

So, along with our discussion, I propose to add two methods to the graphs explicitly handling those cases: `#.mergeNode` & `#.mergeEdge`.

### #.mergeNode

Accepts the following signatures:

```js
// Will add the node if it does not exist, will do nothing otherwise
graph.mergeNode('John');

// Will add the node with the given attributes if it does not exist
// Otherwise, will merge the given attributes with the existing ones
graph.mergeNode('John', {age: 34});

// Will add the node with the given attributes if it does not exist
// Otherwise, will fire the given callback to handle finely the issue
// (like incrementing an existing attribute for instance)
graph.mergeNode('John', {age: 34, occurrences: 1}, (graph, data) => {
  graph.updateNodeAttribute(data.key, 'occurrences', x => x + 1);
});

// Alternatively, there is a variant for when you don't need initial attributes:
graph.mergeNode('John', (graph, data) => {
  // Do what you need...
});
```

### #.mergeEdge

Same semantics than `#.mergeNode`.

---

What do you say?

**Comment by Yomguithereal** [comment]
## Proposition #2

We drop the `onDuplicate*` options because they intrinsically alter the behavior & the nature of the graph, which is dangerous and difficult to reason about.

We add the `#.mergeNode` & `#.mergeEdge` methods but with only arities 1 & 2. Further cases should be handled through basic logic handling which should be easier to reason about & probably as long to write anyway.

**Comment by Yomguithereal** [comment]
Merging methods has been added to `0.2.0` \o/
