### ISSUE TITLE
[layout-forceatlas2] Allow completely ignoring some nodes

### ISSUE THREAD

**Issue by jacomyal** [graphology/graphology#207]
I have a use case in [sigma](https://github.com/jacomyal/sigma.js/tree/v2/src) where I want to hide nodes (using `node.hidden` in my graphology data), and rerun a FA2, but only on the visible part of the graph.

It would be great to have a new option, disabled by default, that would deal with this. Here are two design ideas:

1. Add a new setting `ignoreField`, so that in my case, by adding `{ settings: { ignoreField: "hidden" } }`, the FA2 would completely ignore nodes that have a truthy value for `hidden`;
2. Add a new setting `ignoreNodes` so that I can add `{ settings: { ignoreNodes: (node) => graph.getNodeAttribute(node, "hidden") } }` to ignore the nodes with a truthy value for `hidden` (I prefer this design).

**Comment by Yomguithereal** [comment]
This will be taken care of in #324
