### ISSUE TITLE
Graph.copy() failing on graph where some edges have user keys

### ISSUE THREAD

**Issue by jgg3** [graphology/graphology#213]
I am seeing a failure in copy() when the Graph being copied has some edits where an edge is split into a new edge and a new edge with the prior edges key.  Because I could not find a way to simply change the source/target of an edge without creating a new edge, I delete the old one and create a new one with the same key.  This works, but copy uses export, and export seems to not export keys when they were generated.  This leaves the exported, serialized Graph edges with some keys and some no keys.  Then import generates conflicting keys and we get a failure.

I have searched the issues for this and could not find it.  I am using 0.19.2.  Updated just now to 0.21.1, with only a name change of the edge:  
`UsageGraphError: Graph.addUndirectedEdge: the "0" edge already exists in the graph.`

I understand that I can resort to generating all keys.  But I thought I should mention this because the symptom is a very obscure error that does not make sense for copy.  Why not copy just copy the keys?

**Comment by jgg3** [comment]
OK, here is a case that should work for all versions, but the error is taken from 0.19.2.
```
const Graph = require(`graphology`);
const g = new Graph();
g.addNode('n0');
g.addNode('n1');
g.addNode('n2');
g.addNode('n3');
g.addEdge('n0', 'n1');
g.addEdge('n1', 'n2');
g.addEdge('n2', 'n3');
g.addEdge('n3', 'n0');
const copyNoError = g.copy();
// Do surgery on second edge
const edgeToSplit = g.edges()[1]; 
const newNode = "n12";
g.addNode(newNode);
const e = g.edge('n1', 'n2');
g.dropEdge(e)
g.addEdge('n1', newNode);
g.addEdgeWithKey(e, newNode, 'n2');
// Get the error
const dead = g.copy();
/*
Graph.addDirectedEdgeWithKey: the "_geid1_" edge already exists in the graph.
*/
return 42;

```

**Comment by Yomguithereal** [comment]
Ok, so what I will do first is to fix the `#.copy` method. Then I will have to reflect on the automatically generated key. It used to be some sort of weird string but it actually hurts performance quite a lot vs. basic `0-n` integer ranges (what's more most JS engines are able to aggressively improve performance for this kind of cases). I already had your issue when parsing gexf graphs containing edges without keys AND with incremental keys starting from `0`. I have some solutions in mind that could avoid sacrificing performance again but I need to make some experiments before.
