### ISSUE TITLE
graphology-utils@2.3.1 missing getters.js

### ISSUE THREAD

**Issue by zuiidea** [graphology/graphology#291]
graphology-utils@2.3.1 missing `getters.js`，Leading to `graphology-metrics/centrality/betweenness` not work.

![image](https://user-images.githubusercontent.com/16070518/141098437-97d6bc77-7079-47e9-a3b5-534b5bc83b05.png)

https://unpkg.com/browse/graphology-utils@2.3.1/

**Comment by Yomguithereal** [comment]
Indeed that is unfortunate. Let me fix this now

**Comment by Yomguithereal** [comment]
@zuiidea just released `graphology-utils` v2.3.2 with a fix. A clean reinstall of `graphology-metrics` should work now. I'll let you reopen if this is not the case.

**Comment by zuiidea** [comment]
@Yomguithereal Thank you very much!!
