### ISSUE TITLE
[traversal] depth limit

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#317]

**Comment by dennemark** [comment]
It should be enough to add to each search function the following:

```
      const stepIn = callback(record.node, record.attributes, depth) ?? true;
      if (stepIn ){
          graph.forEachOutboundNeighbor(record.node, neighborCallback);
      }
```
now we can use a callback `dfs(graph, (n, a, depth) => depth < limit)`

I would also propose another improvment, to allow traversal inbound:

```
function dfs(graph, callback, inbound = false) {
    [...]
      const stepIn = callback(record.node, record.attributes, depth) ?? true;
      if (stepIn ){
         if(inbound){
           graph.forEachInboundNeighbor(record.node, neighborCallback);
         }else{
          graph.forEachOutboundNeighbor(record.node, neighborCallback);
         }
      }
    }
  });
```

typing would need to be updated, too
```
export type TraversalCallback<N extends Attributes = Attributes> = (
  key: string,
  attributes: N,
  depth: number
) => boolean | void;
```
```
export function bfsFromNode<N extends Attributes = Attributes>(
  graph: Graph<N>,
  node: unknown,
  callback: TraversalCallback<N>,
  inbound?: boolean
): void;
```


Another improvment would be, to allow kind of accumulator value within bfs. So in each callback function we could evaluate the accumulator, i.e. a weight value for each branch.

**Comment by Yomguithereal** [comment]
@dennemark I have released a v0.3.0 of `graphology-traversal` that includes a way to stop following neighbors when the callback returns `true` and a `mode` option able to change the type of neighbors you want to traverse.

**Comment by dennemark** [comment]
Thanks! Nice and clean implementation!

Even though this issue is closed, I would still like to ask, if you can give a hint on how to implement something like an accumulator value? Maybe to clarify, I don't mean to have an accumulator for the whole search tree, but rather per each branch. So I would need to know the accumulated value or attribute of the prior node. Looking at the code I seem to have no knowledge about the prior node though. I guess one option would be to look ahead within the callback, via in/outbound neighbour and writing an attribute to it, so in this way i can pass knowledge down the search tree.

**Comment by Yomguithereal** [comment]
@dennemark I see your point but whay does a branch mean in this context? Is a branch all of the threads starting from the neighbors of our starting node in each component of the graph? What are you trying to accomplish here? What's the use-case? I am trying to see if a specialized function would be more appropriate for this specific use case (notably because keeping track of the followed path may consume memory I am unwilling to spend in the generic case).

**Comment by dennemark** [comment]
@Yomguithereal I agree, it is probably better to avoid including more logic within the search algorithms.

As a branch I would see a thread going from starting search node to deepest end node.
Lets assume each node has an attribute, such as size. I want to find the thread with with the highest `sum` or `currentSize * depth`. It is a bit like weighted shortest path, but without knowing the end node. Or more like A* search?

**Comment by Yomguithereal** [comment]
> It is a bit like weighted shortest path, but without knowing the end node. 

Isn't this something you can achieve using the `shortest-path` or `simple-path` issue? Or is this more complicated than what I understand.

**Comment by dennemark** [comment]
True, the dijkstra.singleSource might be able to do this. Will need to have a look at it. Thanks a lot!

**Comment by Yomguithereal** [comment]
Would an option of the traversal replacing the depth by the followed path help you in any case (note that since we are traversing various kind of graphs, multi, mixed etc., it might be a challenge to compose with a node path to get the traversed edges in a way)?

**Comment by dennemark** [comment]
This would be an option! But let´s better keep it as is right now, since I am not sure, if the demand arises! dijkstra might be good enough! :) Furthermore, your are keep your memory low ;)
