### ISSUE TITLE
How to use the old-school minified library?

### ISSUE THREAD

**Issue by kikohs** [graphology/graphology#320]
Is there a way to use graphology with a standard <script> JS tag without using ESM? 
Thanks

**Comment by Yomguithereal** [comment]
Sure @kikohs, there are old-school builds of the library in each release here: https://github.com/graphology/graphology/releases

**Comment by Yomguithereal** [comment]
Just note that the -library bundle might be outdated, I need to upgrade it sometime soon.

**Comment by kikohs** [comment]
Thanks, but when you load them, what is the name top-level object to access the library?

graphology.
graph. 

Thanks
?

**Comment by kikohs** [comment]
My bad, I loaded the standard-library without loading the main graphology script.

`graphology` works.

**Comment by Yomguithereal** [comment]
Yes, and the library is exported under a variable named `graphologyLibrary` as exposed here: https://github.com/graphology/graphology/blob/master/src/library/rollup.config.js#L12

**Comment by kMutagene** [comment]
hey @Yomguithereal sorry to zombie this issue, but how exactly should one proceed to reference these files from a play html file? Referencing the links from the release page via script tag does not work.

We can use the umd bundle from the graphology npm package, but the `graphology-library` package does not offer such a bundle so i am quite at a loss here how to do this in a plain html file

**Comment by Yomguithereal** [comment]
@kMutagene the files are available in each github release here: https://github.com/graphology/graphology/releases

There is also one for the library.

In the old times (lol) people downloaded the files and included them alongside their js code as vendors basically. Or they would also rely on CDNs for libraries, but I don't know what is the cool kids of CDNs nowadays sorry.

**Comment by Yomguithereal** [comment]
> A cdn of those 2 files would be exactly what we need, are you distributing them anywhere?

No but I am sure there is half a dozen cdns that pull code from both npm and github out there. For instance jsdelivr hosts `graphology-library`: https://www.jsdelivr.com/package/npm/graphology-library?tab=files&path=dist

Here is the file you seem to search for https://cdn.jsdelivr.net/npm/graphology-library@0.8.0/dist/graphology-library.min.js ?

**Comment by kMutagene** [comment]
@Yomguithereal thank you! I
was under the impression that the library is not available because i was unable to find it on cdnjs, while graphology itself was there. Thanks for that source!
