### ISSUE TITLE
Getting error "Cannot read properties of undefined (reading 'assign') when running forceLayout

### ISSUE THREAD

**Issue by peternhale** [graphology/graphology#341]
Hi, I am working the example for synchronous force layout found in the [docs](https://graphology.github.io/standard-library/layout-force.html#synchronous-layout). I have initialized all nodes n the graph with x and y values of 0.

```
import forceLayout from 'graphology-layout-force';

...
    // To directly assign the positions to the nodes:
    forceLayout.assign(this.graph, {
      maxIterations: 50,
      settings: {
        gravity: 10,
      },
    });
```
Not sure if I have the correct steps, but seems like I am adhering to the library.

graphology@0.23.2
node v16.13.1

Thanks in advance

**Comment by Yomguithereal** [comment]
@peternhale for mathematical reasons, this layout algorithm cannot work if all nodes starts on 0. This is documented for force atlas 2 but not for the basic force layout algorithm it seems. Just initialize your nodes with random positions for instance and it should do the trick (you can use the helper in graphology-layout for that if you want, or use its circular layout as starting positions).

**Comment by Yomguithereal** [comment]
I have added a mention of this in the docs.

**Comment by Yomguithereal** [comment]
This said the error you are mentioning in your issue title seems to point toward a bad import of the library.

**Comment by Yomguithereal** [comment]
Can I close this @peternhale?
