### ISSUE TITLE
[layout-force] shouldSkipNode 

### ISSUE THREAD

**Issue by sim51** [graphology/graphology#343]
https://github.com/graphology/graphology/blob/074e3b77ed9d57c07583205bf554a1d85af8359b/src/layout-force/iterate.js#L25

Should it be : `shouldSkipNode = createNodeValueGetter(shouldSkipNode, false);` ?

**Comment by Yomguithereal** [comment]
You are right indeed :)

**Comment by Yomguithereal** [comment]
v0.2.4 is live with a fix
