### ISSUE TITLE
How do I detect cycles?

### ISSUE THREAD

**Issue by BlueNebulaDev** [graphology/graphology#344]
I need to work with a DAG (Directed Acyclic Graph). It's essential that no cycle gets created.

After considering various Graph libraries from NPM I decided to go with Graphology which looks like one of the best one. However after searching in the doc and GitHub I couldn't find any way to detect or disallow cycles.

Is this feature supported?

**Comment by Yomguithereal** [comment]
Hello @BlueNebulaDev.

> Is this feature supported?

Not yet but it can be easily added and you can already use some workarounds. But first I need to understand some details:

1. Do you need to find specific cycles or do you just need to ensure you have no cycle (in which case a function returning a boolean would be enough)?
2. I don't know of any way to index this problem to make sure the question "will this edge I add create a cycle" can be answered substantially more efficiently than solving the answer for the whole graph (I know tricks but they are a bit costly to implement). Do you really need something more complex than a `hasCycle` function?

**Comment by BlueNebulaDev** [comment]
> Do you need to find specific cycles or do you just need to ensure you have no cycle (in which case a function returning a boolean would be enough)?

I simply need an acyclic graph: any way to achieve this is fine. It's perfectly fine to have an add-edge variant that returns a boolean if the edge can't be added because it would create a cycle. It's even enough to have a function that tells whether there's a cycle already. If such a function existed I could write something like:

```
function addAcyclicEdge(n1, n2) {
  const edge = graph.addEdge(n1, n2);
  if(graph.hasCycles()) {
    graph.dropEdge(edge);
    return null;
  }
  return edge;
}
```

2. I don't know of any way to index this problem to make sure the question "will this edge I add create a cycle" can be answered substantially more efficiently than solving the answer for the whole graph (I know tricks but they are a bit costly to implement). Do you really need something more complex than a hasCycle function?

An `hasCycle` function would be enough. It's expensive true, but I don't know if more efficient methods would exist, and don't need high performance anyways.

3. Are you considering graphs that are single DAGs or that can be forests of disconnected DAGs?

The latter. I would need to create sparse nodes, that could result in disjoined graphs, and then may or may not end up connected together. 

&nbsp;

The DFS module implements the whole logic of an `hasCycle` function, although it uses it in a different way and doesn't expose the information.

**Comment by Yomguithereal** [comment]
I have just added `hasCycle` to `graphology-dag`. I went with the second iterative version using stack peeking, modified to handle disconnected graphs. I would also like to have your input on this code if you find time please: https://github.com/graphology/graphology/blob/master/src/dag/has-cycle.js

**Comment by Yomguithereal** [comment]
Any news @BlueNebulaDev? Should I close the issue?
