### ISSUE TITLE
💡 Feature Idea: Support "combo" style grouping of nodes & links for the data visualization #1201

### ISSUE THREAD

**Issue by cliffordfajardo** [graphology/graphology#349]
Hi Graphology team,

> _Not sure if this is the correct to pose a question/giving feedback regarding graphology _
> _Maybe enabling [Github Discussions tab](https://docs.github.com/en/discussions) for this repository might be a good 😄_

I want to start off by saying:
- I'm a big fan of this graphology's philosophy / initiative to help create a common API that other graph visualization libraries can leverage. 
- I've noticed lots of libraries re-implementing the same layout algorithms or vastly different node API s over & over and this initiative will hopefully help reduce that churn so us graph / data viz engineers can focus on contributing in other areas as well

Given that this library is creating a common interface for graph libraries, I felt this might be the appropriate  place to discuss this idea.

## Feature Idea: Combo grouping of Nodes
As a user rendering lots of data on a graph, specifically related data, a combo feature would help visually simplify the complexity of of the graph by :
- hiding large sets of related nodes initially
- allow the user to click (drilldown) into the node combo to reveal the information, this can happen for any number of levels
- offering a way for users to explore the graph following the principle of progressive disclosure (give details when I need it, hide it when i dont)

## Describe the solution potential solution(s)
- Introduce an addition of a  "combo" API into the library

## Describe alternatives you've considered
The only 2 libraries that I am aware of that offer this functionality are:
- [Open Source] - Ant Visualization group's [G6 Typescript](https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo) library ([Graphin](https://graphin.antv.vision/en-US), a react wrapper around G6) 
- [PAID license] - Cambridge Intelligence's [Keylines](https://cambridge-intelligence.com/keylines/) JS library & [Regraph](https://cambridge-intelligence.com/regraph/) (React wrapper around Keylines library)
- [Unmaintained since 2017-ish] -- [Cisco NextUI Node sets](https://youtu.be/gBsUDu8aucs?t=52)
   - [example](https://github.com/NeXt-UI/next-tutorials/blob/master/tutorials/tutorial-003-01.md)

## Demo Idea (references from other libraries)
![CleanShot 2022-01-10 at 19 20 40](https://user-images.githubusercontent.com/6743796/148875745-3030527a-5309-42b1-bf64-f470f031893c.gif)

https://user-images.githubusercontent.com/6743796/148876265-8cda468d-0d67-4afc-857e-667673b8676e.mp4

https://user-images.githubusercontent.com/6743796/148875939-d1ca9d20-7fcd-42e5-bf37-3a0a9f85fcc6.mp4

![image](https://user-images.githubusercontent.com/6743796/148875546-3ae5049e-39f3-4fb7-b9a8-5783560d7fd1.png)

@Yomguithereal

**Comment by Yomguithereal** [comment]
Hello @cliffordfajardo, while this is a legitimate UX concern etc. I will close this on graphology's side because it is a rendering issue, not a data structure/indexing one. There is nothing from the graphology side preventing you from achieving what you want.

**Comment by cliffordfajardo** [comment]
Update - G6 now supports this
- https://github.com/antvis/G6/discussions/3435
