### ISSUE TITLE
Tests inconsistencies

### ISSUE THREAD

**Issue by luccitan** [graphology/graphology#35]
Inconsistency between the test title and the compare value in [attributes.js](https://github.com/graphology/graphology/blob/master/tests/attributes.js#L163-L168)

Further test inconsistencies should be notified there for grouped modifications

**Comment by Yomguithereal** [comment]
You are right, the title of this test is incorrect and should be "return an empty object". It's a typo due to hasty copy-paste of the getEdgeAttribute one. Feel free to file a PR to fix it. The same issue should be found with node attributes I guess.

**Comment by luccitan** [comment]
**Serialization.js**
- Graph properties not compared to the copy properties in the [emptyCopy test](https://github.com/graphology/graphology/blob/master/tests/serialization.js#L471-L486)

**Instantiation.js**
- I think the two titles of the [hydratation test](https://github.com/graphology/graphology/blob/master/tests/serialization.js#L471-L486) have been swapped, am I right @Yomguithereal ?
- `implementation` variable name has a typo error [there](https://github.com/graphology/graphology/blob/master/tests/instantiation.js#L185)

**read.js, mutation.js, misc.js, known.js**
No tests inconsistencies found.

**attributes.js, event.js, properties.js**
Not checked yet

**Comment by luccitan** [comment]
@Yomguithereal It's noted
I will send a PR with to fix all these inconsistencies at the same time, since there are minor tweaks
