### ISSUE TITLE
Topological sort implementation for graphology dag

### ISSUE THREAD

**Issue by yuvaleliav** [graphology/graphology#381]
Hey, I love this graph lib and happened to need topological sort for this project Im working on, it isn't yet implemented so i did it myself like so

```
function topologicalSortGraphology(directedGraph) {
    const zeroDegreeNodes = directedGraph.filterNodes(node => directedGraph.inDegree(node) === 0)
    const topoQueue = [...zeroDegreeNodes]
    const bfsSeenList = {}
    const orderedNodeIds = []

    while (topoQueue.length !== 0) {
        const currNode = topoQueue.shift()
        orderedNodeIds.push(currNode)

        directedGraph.forEachOutNeighbor(currNode, (neighborId) => {
            const currentNodesAmountSeen = bfsSeenList[neighborId] || 0
            if (directedGraph.inDegree(neighborId) - currentNodesAmountSeen === 1) {
                topoQueue.push(neighborId)
            }
            else {
                bfsSeenList[neighborId] = currentNodesAmountSeen + 1
            }
        })
    }

    return orderedNodeIds
}

```
more than welcome to give some feedback on the code or use it or some of it

**Comment by Yomguithereal** [comment]
Hello @yuvaleliav,

I just pushed a commit adding a `topologicalSort` function based on your code and [Kahn's algorithm](https://en.wikipedia.org/wiki/Topological_sorting): https://github.com/graphology/graphology/commit/abea317159fb3955656556e1aca19f4360ee5bbb

Can you check the code and tell me whether it looks good to you? I would publish a new version of `graphology-dag` afterwards.

**Comment by yuvaleliav** [comment]
went through all of it! looks awesome!

**Comment by Yomguithereal** [comment]
v0.2.0 of `graphology-dag` is now live \o/
