### ISSUE TITLE
[forceatlas2] Add Dissuade Hubs

### ISSUE THREAD

**Issue by tom-osint** [graphology/graphology#384]
For network analysis it would be incredible useful to have the "dissuade hubs" setting implemented in graphology's implementation of forceatlas2.

The attraction force can be found in this journal: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679

**Comment by Yomguithereal** [comment]
@tom-osint the javascript code of graphology's forceatlas2 layout was initially written by this paper's principal author. I believe in this implementation the dissuade hubs setting is named `outboundAttractionDistribution`.

**Comment by tom-osint** [comment]
> @tom-osint the javascript code of graphology's forceatlas2 layout was initially written by this paper's principal author. I believe in this implementation the dissuade hubs setting is named `outboundAttractionDistribution`: https://graphology.github.io/standard-library/layout-forceatlas2.html#settings.

Cheers. I'll check this setting out.
