### ISSUE TITLE
Add depth option to allSimplePaths

### ISSUE THREAD

**Issue by pokrovskyy** [graphology/graphology#391]
`allSimplePaths` from https://github.com/graphology/graphology/tree/master/src/simple-path is missing an important `depth` argument to limit the traversal. This becomes a significant performance-wise limitation when working with relatively large and well-connected graphs. Please consider adding it

**Comment by pokrovskyy** [comment]
See my suggested simplistic implementation https://github.com/graphology/graphology/pull/392

**Comment by Yomguithereal** [comment]
@pokrovskyy I have switched to an object of options. v0.2.0 of `graphology-simple-path` should now be available on npm.
