### ISSUE TITLE
Typed attributes

### ISSUE THREAD

**Issue by l-x-u** [graphology/graphology#394]
Hello, I have started to use graphology and was pleased to see there is TypeScript support. I was wondering, when creating a graph, is it possible for the programmer to somehow supply types to specify the types of the attributes for the graph, nodes, and edges? I guess what I am thinking of would be a way to use generics to get type checking for graph attributes. Apologies if I missed information on this subject that is available elsewhere!

**Comment by Yomguithereal** [comment]
Hello @l-x-u. The graph types already come with 3 optional generics allowing you to type, in order: node attributes, edge attributes then graph attributes.

**Comment by l-x-u** [comment]
Oh, wonderful! Thanks for the fast response. It might be worth adding a note about that in the [instantiation section](https://graphology.github.io/instantiation.html) of the documentation to make the generics a bit more discoverable.

**Comment by Yomguithereal** [comment]
You are right indeed. Or around the homepage of the docs in the TS section maybe. Do you want to contribute a paragraph to the docs I could merge?

**Comment by l-x-u** [comment]
Sounds good, I have posted a PR: https://github.com/graphology/graphology.github.io/pull/1

**Comment by Yomguithereal** [comment]
@l-x-u I have updated the docs
