### ISSUE TITLE
Wrong typing for from method

### ISSUE THREAD

**Issue by kmalski** [graphology/graphology#395]
Hi, I have found that static `from` method has incorrect typing. In the [documentation](https://graphology.github.io/instantiation.html#static-from-method) and in the [implementation ](https://github.com/graphology/graphology/blob/master/src/graphology/src/index.js) user is able to pass `options` as an second argument but in the [type definition](https://github.com/graphology/graphology/blob/master/src/types/index.d.ts) this argument is missing.

**Comment by Yomguithereal** [comment]
You are right indeed @kmalski. v0.24.4 is now live on npm with the fix.
