### ISSUE TITLE
How to use graphology using script tag in HTML + Javascript?

### ISSUE THREAD

**Issue by atharvashukla** [graphology/graphology#399]
I have the following starter code for an `index.html` file with `graphology.min.js` downloaded from the releases section on the Github.

`index.html`:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <script src="graphology.min.js"></script>
    <script src="main.js"></script>
  </body>
</html>
```

I want use to graphology in the `main.js` file, however `new Graph()` does not exist. 

`main.js`

```
console.log(new Graph());
```

How should I instantiate graphology?

**Comment by Yomguithereal** [comment]
Hello @atharvashukla 

> How should I instantiate graphology?

the legacy bundle exports everything as a global `graphology` variable. So:

```js
new graphology.Graph();
```

Or you can also do the following:

```js
const {Graph} = graphology;
```

I will try to add the relevant documentation to the homepage so that people are not confused.

**Comment by Yomguithereal** [comment]
I have updated the docs so this is clearer.

**Comment by atharvashukla** [comment]
Thank you!
