### ISSUE TITLE
Question: What are some good first start issues ?

### ISSUE THREAD

**Issue by cliffordfajardo** [graphology/graphology#415]
Hi @Yomguithereal,
Do you have any recommendations on any first good issues or bugs for beginners?

**Comment by Yomguithereal** [comment]
Hello @cliffordfajardo, I have labeled some issues that might be easier to deal with than the other here: https://github.com/graphology/graphology/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Don't hesitate to ask me if some are unclear.

Some other issues are not that complex but are tangled in other refactors and cannot be done earlier.
