### ISSUE TITLE
Export to /dist for online CDNs

### ISSUE THREAD

**Issue by kikohs** [graphology/graphology#417]
Hello,
I'm trying to use graphology-library.min.js from jsDeliver but can't access the release files.
Would it be possible to put the releases in a /dist folder which could be indexed by the different CDNs?

Thank you

**Comment by kikohs** [comment]
Hi, yes for `graphlogy` but not for `graphology-library` where you have parsers, layouts etc. I need the `libraries` as well. 
Thank you.

**Comment by Yomguithereal** [comment]
For the library you have this: https://www.jsdelivr.com/package/npm/graphology-library?path=dist and https://cdn.jsdelivr.net/npm/graphology-library@0.7.1/dist/graphology-library.min.js

**Comment by kikohs** [comment]
Awesome! Thank you very much.
