### ISSUE TITLE
Lazily add edges

### ISSUE THREAD

**Issue by strarsis** [graphology/graphology#423]
When an edge is added, non-existing nodes are added automatically.

However, sometimes the edges of a node are added while the other nodes, including those to be connected, haven't been added yet. Therefore it would be very helpful if those edges were added without creating non-existing nodes.
Even better: An event is emitted when those yet non-existing nodes are queries, so they can be dynamically added (e.g. by network request).

**Comment by Yomguithereal** [comment]
Hello @strarsis,

> When an edge is added, non-existing nodes are added automatically.

That's true only when using `#.mergeEdge` or `#.updateEdge`. `#.addEdge` will throw if given an unknown node.

> However, sometimes the edges of a node are added while the other nodes, including those to be connected, haven't been added yet. Therefore it would be very helpful if those edges were added without creating non-existing nodes.
Even better: An event is emitted when those yet non-existing nodes are queries, so they can be dynamically added (e.g. by network request).

It does not really make sense to create edges without both extremities (those are sometimes called stubs but are not straightforward to represent in memory or add unnecessary constraints). You can very well create those edges with `#.mergeEdge` or `#.updateEdge` and give the nodes its attributes later (or fetch them at once as you propose, by relying on the information given by the return value of both those methods).

**Comment by FunkMonkey** [comment]
@Yomguithereal Is there some way to detect if a node was created by `mergeEdge` or `updateEdge`? I can imagine that we could check if `attributes` is an empty object with no keys, e.g. see [Stackoverflow](https://stackoverflow.com/questions/679915/how-do-i-test-for-an-empty-javascript-object) . Can you think of any other way (which may also be more performant)?

I am also trying to create partial graphs, which may have edges between non-existent nodes in the graph (non-existent at least until multiple partial graphs are merged)...

Thank you!

**Comment by Yomguithereal** [comment]
@FunkMonkey as documented for example here for mergeEdge: https://graphology.github.io/mutation.html#mergeedge those methods all return a array/tuple of sorts indicating if something was created.

**Comment by FunkMonkey** [comment]
@Yomguithereal thanks for the quick reply! I meant more like: if I already get a graph on which `mergeEdge` was used, what is the best way to find out if a node was created implicitly using such a function? I assume there is no flag set in graphology internally for implicitly created nodes, right? And the attributes are an empty object and not `null` (which would also make it easier to find that out), so I must probably "simply" check for emptyness, correct?

**Comment by Yomguithereal** [comment]
> if I already get a graph on which mergeEdge was used

Aren't you the one building said graph using `mergeEdge`? If so, why do you try to assess if some nodes were implicitly created after the fact, rather than when using `mergeEdge`?

> I assume there is no flag set in graphology internally for implicitly created nodes, right?

No there isn't, as it would incur a cost most people really don't need to pay. But you can very well create your own by setting some attribute on the nodes you explicitly created. This attribute will naturally be absent from the nodes that were implicitly created. This is of course a variant of checking whether the node attributes are empty indeed (which does not work if you don't intend to give node attributes whatsoever).

**Comment by FunkMonkey** [comment]
> Aren't you the one building said graph using mergeEdge? If so, why do you try to assess if some nodes were implicitly created after the fact, rather than when using mergeEdge?

Well yes, but I was curious what options I actually have...

> No there isn't, as it would incur a cost most people really don't need to pay. 

Makes total sense!

>  No there isn't, as it would incur a cost most people really don't need to pay. But you can very well create your own by setting some attribute on the nodes you explicitly created. This attribute will naturally be absent from the nodes that were implicitly created. This is of course a variant of checking whether the node attributes are empty indeed (which does not work if you don't intend to give node attributes whatsoever).

Guess I'll go this route then, similarly to what @strarsis proposed with placeholder attributes.

Thanks again for the response!
