### ISSUE TITLE
Unhandled Rejection (TypeError): Object(...) is not a function

### ISSUE THREAD

**Issue by michaelbdavid** [graphology/graphology#430]
Attempting to pull in 

```
import Graph from 'graphology';
import {karateClub} from 'graphology-generators/karate-club';
// Alternatively, if you only want to load relevant code
// import karateClub from 'graphology-generators/social/karate-club';

// Generating the graph
const graph = karateClub(Graph);
```

Seeing:
```Unhandled Rejection (TypeError): Object(...) is not a function
const g = Object(graphology_generators__WEBPACK_IMPORTED_MODULE_14__["karateClub"])(graphology__WEBPACK_IMPORTED_MODULE_11___default.a);
```

seems to give this error for all the generators.  Graphology working fine for all the layouts.  

```
"graphology": "^0.25.0",
"graphology-generators": "^0.11.2",
"graphology-layout": "^0.6.1",
"graphology-layout-force": "^0.2.4",
"graphology-types": "^0.24.5",
```

**Comment by Yomguithereal** [comment]
Hello @michaelbdavid, without more information I won't be able to help you since your issue seems to be tied with webpack packaging mostly.

**Comment by michaelbdavid** [comment]
I'm just using the default config provided by create-react-app.  Is there any other details that you would need?  Using TS 
"@types/webpack-env": "^1.16.0",

**Comment by Yomguithereal** [comment]
This does not help much no. What I am trying to say is that your problem comes mostly from either: 1. create-react-app, 2. webpack or 3. TypeScript, but not `graphology` itself. One thing you could do is provide a repository containing your problem as a minimal reproducible case so I can try something if I find some time.
