### ISSUE TITLE
Callback Function Arguments

### ISSUE THREAD

**Issue by DynamicCoder2** [graphology/graphology#448]
When hitting the graph with a function e.g. `#.forEachEdge()` and using a callback function within it, the order of the arguments seem to affect their value as demonstrated with the example code below:

```js
import Graph from "graphology";
const graph = new Graph({
  multi: true
});

graph.addNode("1");
graph.addNode("2");
graph.addNode("3");

graph.addEdge("1", "2", { option: "a" });
graph.addEdge("1", "2", { option: "b" });
graph.addEdge("1", "3", { option: "c" });
graph.addEdge("2", "3", { option: "d" });

graph.forEachEdge("1", "2", (attributes) => {
  console.log(attributes);
});

console.log("-- Separator --");

graph.forEachEdge("1", "2", (edge, attributes) => {
  console.log(attributes);
});
```

Console is:
```js
geid_113_1 
geid_113_0 
-- Separator -- 
{option: "b"}
{option: "a"}
```

Just wondering if this is intended behaviour or a bug?
Thanks for an amazing library :)

**Comment by Yomguithereal** [comment]
The number of arguments given to `#.forEach*Edge` methods should not have an impact on the arguments given to the callback (edge, then attributes, then source key etc.). So if this actually happen this would be a bug. This said, your example does not demonstrate such a bug at all, as you named your first argument "attributes" in the first instance while it should be the edge key, so the log output seems correct to me.

**Comment by DynamicCoder2** [comment]
I see so if I only wanted to access the attributes argument in my callback function I would still put `(edge, attributes)`, since otherwise it is working correctly and not a bug.

**Comment by Yomguithereal** [comment]
Yes, this is how functions work in JavaScript. The name of the callback argument is arbitrary as you are the one giving it. Only the order is important. So if you rename the first argument "attributes", it won't change the fact that it is in fact the edge key. If you are ok with using more recent JavaScript version you can also use the entries method that yield objects easier to destructure to access the piece of information you need, like so:

```js
for (const {attributes} of graph.edgeEntries("1", "2")) {
  console.log(attributes);
}
```

**Comment by DynamicCoder2** [comment]
Thank you very much for your kind explanation
