### ISSUE TITLE
Please export type GraphEvents

### ISSUE THREAD

**Issue by Vithanco** [graphology/graphology#450]
I would like to observe two graphs closely. In order to have this in a clean implementation would I like to create a handler like described here: https://stackoverflow.com/questions/32031936/code-efficiency-in-node-js-for-multiple-events-listeners 
this would be: 

function addHandler(evName, moreParams here) {
  localEvents.on(evName, function(request, reply) {
    console.log("inside event for %s", evName);
    //do my thing
  });
}

addHandler('nodeAdded', ...);
addHandler('edgeAdded', ...);
addHandler('nodeDropped', ...);

as I use Typescript, I would like to give the evName parameter the right type. But it's not exported, so I cannot use it. 

I hope this makes sense. 
BTW, great library. Thanks a lot!

**Comment by Yomguithereal** [comment]
@Vithanco `GraphEvents` is now exported from `graphology-types` v0.24.6.
