### ISSUE TITLE
hidden nodes completely removed from graph

### ISSUE THREAD

**Issue by jronallo** [graphology/graphology#454]
It appears that setting the "hidden" node attribute to true removes the node from the graph. What I expected to happen was that hidden nodes would still be included in the graph but not display and be skipped over for layout.

**Comment by Yomguithereal** [comment]
> It appears that setting the "hidden" node attribute to true removes the node from the graph.

I don't know what you mean. Can you provide an minimal reproducible example of what you observe?

> What I expected to happen was that hidden nodes would still be included in the graph but not display and be skipped over for layout.

`graphology` does not display graphs, it is but a data structure. Are you sure you are not in fact intending this issue for sigma.js or something else of the kind?

**Comment by jronallo** [comment]
Yes, you are correct. I was using the graphology interface to set the "hidden" value, but with only graphology setting an attribute of "hidden" maintains the order of the graph. But in the sigma.js context it appears that setting the hidden attribute drops the node.
