### ISSUE TITLE
addNodeWithKey

### ISSUE THREAD

**Issue by Vithanco** [graphology/graphology#455]
Is there a reason why there is an `addEdgeWithKey` but not an `addNodeWithKey`? I try to restore a graph with the same keys as I use them in another part of the software. Without the addNodeWithKey the graphs will be different.

**Comment by Yomguithereal** [comment]
nodes always have a key. edges do not. `addNode` takes a key and optional attributes already. `addEdgeWithKey` is longer because most people don't care about edge keys as they poll the relevant info using source, target combos.

**Comment by Vithanco** [comment]
Thanks! I wasn't looking closely enough. The parameter is called node, but https://graphology.github.io/mutation.html#addnode clearly states it's the key, so the mistake was all mine. 

Pedantic me has a suggestion to improve documentation: What is going to happen if the same key is used again?
Generally the documentation could note these edge cases. Sometimes is says so (https://graphology.github.io/attributes.html#getattribute in first line), but sometimes it's not provided (https://graphology.github.io/attributes.html#getattributes). https://graphology.github.io/attributes.html#getnodeattribute states that it will return `undefined` if not found. I assume that it will return `undefined` in both cases, missing node or missing attribute. 

Again, this is pedantic me. Not really needed (yet), but makes the use of your nice library much easier. Feel free to ignore this comment :-)

**Comment by Vithanco** [comment]
Closing this, no action required. You might find above comments relevant. If requested, then I could try to improve descriptions.
