### ISSUE TITLE
In a directed graph, the set of edges from A->B is not the same as the set from B->A

### ISSUE THREAD

**Issue by Vithanco** [graphology/graphology#457]
I was expecting that in a directed graph, the set of edges from A->B is not the same as the set from B->A. But that is the outcome of the current implementation (graphology V0.25.1). 

I created this little test:
```
const G = require('graphology')

const graph = new G.Graph({multi: true, directed: true})

const A = graph.addNode('A')
const B = graph.addNode('B')
graph.addEdge(A, B, {name: 'forward'})
graph.addEdge(B, A, {name: 'backward'})

graph.edges(A, B).forEach(edge => {console.log(graph.getEdgeAttribute(edge, 'name'))})
```

resulting in this outcome: 
```
backward
forward
```

Or is this the correct result?

**Comment by Vithanco** [comment]
on a secondary note, it is odd that the wrong (?) outcome even comes first in list.

**Comment by Yomguithereal** [comment]
> Or is this the correct result?

Yes. I think you mean to use `#.outEdges` or `#.inEdges`. In a directed graph, `#.edges` is the union of both incoming & outgoing edges.
