### ISSUE TITLE
Using standard library to export PNG or SVG

### ISSUE THREAD

**Issue by abundis-rmn2** [graphology/graphology#460]
Is there a way to export any kind of image as PNG or SVG usint the standard library:

```<!-- To use the standard library -->
<script src="graphology-library.min.js"></script>
<!-- This exposes a global variable named "graphologyLibrary" -->
<script>
  const density = graphologyLibrary.metrics.graph.density(graph);
</script>```


For example 
` graphologyLibrary.canvas(foo);`

**Comment by Yomguithereal** [comment]
Hello @abundis-rmn2, `graphology` standard library has two relevant libraries for what you want: 1. [`graphology-canvas`](https://graphology.github.io/standard-library/canvas) and 2. [`graphology-svg`](https://graphology.github.io/standard-library/svg).

They were not included yet in the meta-package `graphology-library` so I added them this morning. Just note that 1. I don't think `graphology-svg` can work in a web browser right now (without loading the subfile `/renderers` which is not accessible without proper js packaging) and that both are not feature-complete and might not suit your use case.

**Comment by abundis-rmn2** [comment]
I give it a tray and works; am copy and pasting the snippet for newbies, as me, looking for this.

Create canvas in html

```
<canvas id="test" width="2000" height="2000">
</canvas>
```
Make context in JS and then call library, I set padding as the width and the height to center everything, i don't know if thats right but it works.

```
const canvas = document.getElementById("test");
const ctx = canvas.getContext("2d");
graphologyLibrary.canvas.render(graph, ctx, {padding:2000})
```
![image](https://user-images.githubusercontent.com/67477259/222803932-1106a80f-5703-4eba-ae7b-05c327904ccf.png)
