### ISSUE TITLE
Please add topological sort that returns results groups of nodes by generation

### ISSUE THREAD

**Issue by matthewadams** [graphology/graphology#464]
Please add a topological sorting function that returns a group of nodes per entry instead of a flat array, similar to the behavior of https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.topological_generations.html.

**Comment by Yomguithereal** [comment]
@matthewadams generation-related utils have been added to `graphology-dag` by @16arpi. They are published as part of `0.3.0`.
