### ISSUE TITLE
Sigma: Coordinates of node are invalid. A node must have a numeric 'x' and 'y' attribute.

### ISSUE THREAD

**Issue by wthrajat** [graphology/graphology#471]
Hi. Please let me know if I should post issues like this elsewhere.

I am working on a project that require me to generate network graphs using sigma and graphology.
Regarding the nodes and edges dataset, I cannot manually put `x` and `y` coordinates in my nodes attributes. (My dataset is automatically generated and I cannot manually put these coordinated for each node. It is not practical at all)

Hence the only way for me to build the graph is to use a layout.
I am using FA2 layout, and the docs did warn me that in order to use this layout, you must have the `x` and `y` coordinates. It suggests that we can initialise them using `random-layout`.
However, I am not sure why I keep getting the error. I have implemented the random layout as well.
[Here is my codeSandbox fork](https://codesandbox.io/s/layout-experiment-vq1xec)

How do I proceed from here? I am using random layout still not able to randomize the coordinates.
And if I remove the coordinates from the nodes, I get the above error (in the title).

Sorry if this sounds more of a question than an issue. And please let me know if I should post these types of "issues" elsewhere (and if you could let be know where should I, then it'd me much appreciated)

**Comment by Yomguithereal** [comment]
@wthrajat I don't understand the problem you are having. What's more the codesandbox link you gave point to a working example without error so I am at a loss here. Can you provide a minimal reproducible example of the problem you are trying to solve here?

**Comment by wthrajat** [comment]
@Yomguithereal Yes the problem isn't visible in the sandbox.
However inside the `data.json` file, if you remove any of the node's `x` and `y` attribute then it gives the error that is on the title.
Let me update the sandbox code.
```
{
  "nodes": [
    {
      "key": "2",
      "attributes": {
        "x": 248.45229,
        "y": 52.22656,
        "size": 16.714285,
        "label": "Kroos",
        "color": "#BB100A"
      }
 }
```
For example, if I remove the coordinates from this node, I get the error.
And I will very soon deal with the data that will not contain these `x and y` coordinates. So I need to find a solution.

**Comment by Yomguithereal** [comment]
Yes sigma cannot render a graph without node positions. You need to provide one yourself. Typically people would assign the graph a random layout, then apply forceatlas2 to get likely positions. Note that most force layout algorithms don't have a deterministic stop condition so people tend to develop UIs letting users control the layout to tell when to stop. If you don't want that, you can always run a fixed number of FA2 iterations and hope for the best.

Here is how you would do so:

```js
import {random} from 'graphology-layout'
import forceAtlas2 from 'graphology-layout-forceatlas2'; 

random.assign(yourGraph);
forceAtlas2.assign(yourGraph, {iterations: 100, settings: {...}});
```

**Comment by wthrajat** [comment]
> You need to provide one yourself

Thats what I am worried about.
I cannot put co-ordinates to every node because my project has many (sometimes even 1000s of nodes). So I am confused what should I put in the
```
"attributes": {
        "x": " ",
        "y": " "
```
If I leave the `x` and `y` blank like this:
```
{
  "nodes": [
    {
      "key": "2",
      "attributes": {
        "size": 16,
        "label": "Kroos",
        "color": "red"
      }
 }
 ```
 Then I get the error `Sigma: Coordinates of node are invalid. A node must have a numeric 'x' and 'y' attribute.`
 
 I understand that you're suggesting to use the `random-layout` (I have even used it on my [sandbox](https://codesandbox.io/s/layout-experiment-vq1xec) but that didn't change my `data.json` file)
 What I expected after using the random layout: That there will be random `x` and `y` values in my `data.json`.

**Comment by wthrajat** [comment]
@Yomguithereal I solved the issue by initialising the x and y coordinates as follows:
```
const radius = 200; // Radius of the circle
const centerX = 300; // X-coordinate of the center of the circle
const centerY = 300; // Y-coordinate of the center of the circle
const angleIncrement = (4 * Math.PI) / graph.order; // Angle increment for each node
let i = 0;
graph.forEachNode((node) => {
  const angle = i * angleIncrement; // Calculate the angle for the current node
  const x = centerX + radius * Math.cos(angle); // Calculate x-coordinate using cosine
  const y = centerY + radius * Math.sin(angle); // Calculate y-coordinate using sine
  graph.setNodeAttribute(node, "x", x);
  graph.setNodeAttribute(node, "y", y);
  i++;
});
```
Thanks for your help. Now that the values are initialised, I am able to apply any layout :)
