### ISSUE TITLE
Error when I drop a node

### ISSUE THREAD

**Issue by jMoulis** [graphology/graphology#474]
Hello,
I'm brand new using the lib.
I'm trying to add, for testing purpose, a doubleclick on a node to drop it. But I catch th following error:
`Uncaught NotFoundGraphError: Graph.neighbors: could not find the "48309" node in the graph.`, which seems pretty normal, because I just deleted.
I tried to use a cleaning function in the `graph.on('nodeDropped')`, but I can't get it working.
Can you help me?
Best regards

**Comment by Yomguithereal** [comment]
I don't understand what you need sorry. Your error tells you you are trying to access the neighbors of a node that does not exist in the graph, which is normal if you dropped the node earlier. This is not an error with the library but with your code. You seem to hold a reference to an older node which you need to cleanup. Can you explain what isn't working with the `nodeDropped` event? Alternatively you can also check a node still exists using the `hasNode` method of the graph before attempting to retrieve its neighbors.

**Comment by jMoulis** [comment]
My bad. actually, I don't have a function written by myself, which try to access neighbors. But I guess, the pb is not from graphology, but sigma which I use with react-sigma. It is probably something that wrongly configured.
I thought that I had to clean something a the `nodeDropped` like I do when I drop an edge, I have a `edgeDropped` callback function to drop all orphans nodes. But sorry for bothering, and thanks for your quick feedback

**Comment by Yomguithereal** [comment]
Good luck than @jMoulis :) Hope you find the way to fix the situation.
