### ISSUE TITLE
Graph.addDirectedEdgeWithKey: target node not found when there are multiple target for a given source

### ISSUE THREAD

**Issue by wthrajat** [graphology/graphology#475]
In my dataset, I have many documents/pages of a wiki software (in the form of nodes) which contains many interconnected documents/pages that I need to show through links (or edges) in a network graph.
Hence, there can be multiple edges for a given node.

In my working example here: [Code Sandbox Link](https://codesandbox.io/s/layout-experiment-vq1xec?file=/data.json:11457-11679), I get the error `Graph.addDirectedEdgeWithKey: target node not found` because the `target` attribute contains so many "targets".

```
"target": [
        "document:xwiki:Sandbox.TestPage3",
        "document:xwiki:Sandbox.TestPage2",
        "document:xwiki:Sandbox.TestPage1",
        "document:xwiki:XWiki.XWikiSyntax",
        "document:xwiki:Main.WebHome"
      ],
      "source": "document:xwiki:Sandbox.WebHome"
```

My question is: Is there a way in graphology so that we can connect multiple targets to a source node?
The code works if I remove many entries from inside the `target` attribute like this.

```
"target": [
        "document:xwiki:Sandbox.TestPage3"
      ],
      "source": "document:xwiki:Sandbox.WebHome"
```

But I cannot manually delete these entries since this `data.json` is automatically generated at the backend.
One possible solution I know is to create a new pair of `edge` for every value of `target`.

**Comment by Yomguithereal** [comment]
> My question is: Is there a way in graphology so that we can connect multiple targets to a source node?

Yes you can just do a loop and add the edges one by one, that's all :).

Your example of JSON will not work out-of-the-box with graphology so yes you can either 1. create one edge per pair or 2. create your own JSON format and process it to create the graph out of it which is not very difficult to do.

**Comment by wthrajat** [comment]
Thanks.
Are you aware of any documentation that could help me with solution 2? (my own json format).
I looked at various codesandbox sigmajs examples but more or less, all JSON files are same.

**Comment by Yomguithereal** [comment]
> Are you aware of any documentation that could help me with solution 2? (my own json **format).

Not really. JSON is just a way to organize, serialize and send over the wire complex data. It's no different that organizing your data when programming by using values, objects and arrays. It's basic programming knowledge and has nothing to do with `graphology` nor `sigma`.

For instance, let's say you created the following JSON file:

```json
{
  "nodes": ["one", "two", "three"],
  "edges": [
    {"source": "one", "targets": ["two", "three"]},
    {"source": "two", "targets": ["three"]}
  ]
}
```

Then creating a graph from it is just a matter of doing the following:

```js
// Adding nodes
data.nodes.forEach(node => graph.addNode(node));

// Adding edges
data.edhes.forEach(edge => {
  edge.targets.forEach(target => {
    graph.addEdge(edge.source, target);
  });
});
```

`graphology` has its own builtin generic JSON format that is useful for most purposes but it really is not that complicated to create your own to tailor it to more specific needs.

**Comment by wthrajat** [comment]
Thanks @Yomguithereal for this. The issue is now solved, I created my own format :)
