### ISSUE TITLE
Question re: _edges.get()

### ISSUE THREAD

**Issue by flowt-au** [graphology/graphology#476]
I am setting a unique key for each edge and would like to be able to get the edge by that key.

I couldn't find a method that did that. Digging into the code revealed I could do eg
```
const edgeData = this.graph._edges.get(edgeKey);
```
which works great. 

But it begs the question as to why there isn't a `graph.getEdgeByKey()` type method. Or am I missing something really obvious here?

Thanks for your great library.

Murray

**Comment by Yomguithereal** [comment]
@flowt-au what do you mean by getting an edge by key? If you mean attributes attached to the edge then you can use `#.getEdgeAttributes(key)`. If you mean the edge's source & target you can use `#.source` or `#.target` or `#.extremities` etc.

**Comment by flowt-au** [comment]
Thanks for your quick response.

Yes, all those functions can be used and that is what I was doing. In my tiredness I missed the fact that `getEdgeAttributes()` also returns the source and target ids (which I also needed) and was using `extremities` to get that info. Of course, this morning I see my mistake.

So, closing this question. 

Much appreciated,
Murray
