### ISSUE TITLE
Compound Spring Embedder, combi of vertical & horizontal layouts

### ISSUE THREAD

**Issue by flieks** [graphology/graphology#477]
Hi,

I would like to use sigma and have the capability to set certain nodes on a vertical line and align others on a horizontal line. This would essentially allow us to generate single wire diagrams and even connect multiple SWDs to each other.

A [plugin](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose) on cytoscape is able to do it 
<img width="336" alt="image" src="https://github.com/graphology/graphology/assets/5032389/ea9ee715-c9f2-4a10-a3a2-55d3062cca02">

but i would prefer using Sigma. Is this possible with graphology and sigma ?

**Comment by Yomguithereal** [comment]
> Is this possible with graphology and sigma ?

Sure, it could be implemented in `graphology` but it requires quite some time to dedicate to this and I don't specifically have any incentive to do it myself. But if you want to take a dab at it and open a PR I would review it gladly.

> but i would prefer using Sigma. 

I don't want to play against my team here but Sigma was not really designed for this particular kind of use-cases, contrary to graphviz/dot, d3 or cytoscape. Why do you feel Sigma would be better for you? Do you have a very large number of nodes or performance issues?
