### ISSUE TITLE
Labels not showing in FA2 layout unless we really zoom-in

### ISSUE THREAD

**Issue by wthrajat** [graphology/graphology#478]
For a large dataset, the labels are not showing. Only thousands of nodes are visible.
The only way to see labels is to zoom in into a group of nodes and then the labels will be visible for those group of nodes only.

You can see the [live demo here in my CodeSandbox link](https://codesandbox.io/s/function-export-7y984p) as my dataset is very large.

I have also tinkered with the `labels threshold` button at the bottom of the screen. It only shows some labels.
I understand that the view area of the graph container is limited. But do you have any way to work this out?
Or do you have any recommendation for graph settings options that will make the graph look better?
Thanks a lot!

**Comment by Yomguithereal** [comment]
Sorry @wthrajat I must close this issue it has nothing to do with `graphology` but with sigma.js. As a hint check out those settings: https://github.com/jacomyal/sigma.js/blob/main/src/settings.ts#L48-L51

**Comment by wthrajat** [comment]
So sorry I didn't know that these settings were on Sigmajs as they don't have proper docs, but I should have been careful.
One last thing you could you could tell me, how do I know what all options are available for a setting?
eg, `defaultEdgeType: "line"`
How can I know what all options are available to me? I tried pressing `Ctrl + Space` for suggestions to show up but it didn't show anything useful. I also tried this with an IDE (VSCode) but it didn't work.

**Comment by sim51** [comment]
"type" for edge and define are defined by the name of the program that are loaded.
Program are in the settings here : https://github.com/jacomyal/sigma.js/blob/main/src/settings.ts#L67C3-L69

And the default values : https://github.com/jacomyal/sigma.js/blob/main/src/settings.ts#L125-L132
