### ISSUE TITLE
Best way to handle click events when clicking on nodes without using React

### ISSUE THREAD

**Issue by wthrajat** [graphology/graphology#479]
Hi. I need to open a node's URL when the user click on it.
My graph data look like:
```
"nodes": [
    {
      "key": "key_here",
      "attributes": {
        "pageURL": "www.example.com"
      }
    } so on...
]
```
Could you tell me what could be the best way to do this?
I checked on the internet and found out that [Sigmajs](www.sigmajs.org) site uses React to handle click events as:
```
useEffect(() => {
    registerEvents({
      clickNode({ node }) {
        if (!graph.getNodeAttribute(node, "hidden")) {
          window.open(graph.getNodeAttribute(node, "pageURL"), "_blank");
        }
      }
```
It uses `RegisterEvents, useEffect` to achieve this.
I am not using react or react-sigma in my project, is there a way to do it without using react or react components?
[Here is my CodeSandbox link](https://codesandbox.io/s/function-export-7y984p?file=/index.ts) if that helps
Thanks!

**Comment by wthrajat** [comment]
Also, I am using the functionality that helps us to drag nodes here and there when we click and hold on a node.
I was wondering if `clicking on nodes to open their URL` feature would clash with the `drag nodes` feature?
(for example, the [demo at sigmajs site](https://www.sigmajs.org/) let us click the nodes to open their URL, but we cannot drag nodes there, hence I was confused is it even possible to have both the functionality)
Is there a way to distinguish them?
Thanks!

**Comment by wthrajat** [comment]
Edit: Hi. I did it on my own.
```
  const renderer = new Sigma(graph, container);

  renderer.on("clickNode", ({ node }) => {
    if (!graph.getNodeAttribute(node, "hidden")) {
      window.open(graph.getNodeAttribute(node, "pageURL"), "_blank");
    }
  });
```
It works just fine!
(Though when I am dragging, the dragging works but when I release my mouse click, the node URL is opened even though my intention was just to drag nodes, NOT to open the node's URL)

**Comment by Yomguithereal** [comment]
Once again @wthrajat this has nothing to do with graphology sorry. As a hint, you need to track the state of the mouse when you press to avoid firing opening the window when dragging.
