### ISSUE TITLE
'Graph.addNode: invalid attributes' for class instances

### ISSUE THREAD

**Issue by skywarth** [graphology/graphology#487]
Hi,

I'm receiving `Uncaught InvalidArgumentsGraphError: Graph.addNode: invalid attributes. Expecting an object but got "[object Object]"` error upon trying to add a class instance as node attribute. It is a rather simple class, just some attributes and accessors.

```
                const countryNode=new CountryNode(
                country.cca3,
                new Coordinate(country.latlng[0],country.latlng[1]),
                country.name.common,
                country.name.official,
                country.region,
                country.subregion,
                country.flag,
                country
                )
            this.graphInstance.addNode(country.cca3,countryNode);
```

How can I resolve this, I really need to pass a class instance as node attribute, it would help me greatly in terms of refactoring. Is there a workaround ? 

I'm using the minified `graphology.min.js` as library source. I can't remember the exact version unfortunately, but it was fairly recent.

Thank you

**Comment by Yomguithereal** [comment]
Hello @skywarth, for multiple reasons, ranging from its usage by interactive web renderer & serialization issues, `graphology` does not allow anything other than plain objects as attributes.

> Is there a workaround ?

Sure, why not have an attribute store your custom class? Something like:

```js
this.graphInstance.addNode(country.cca3, {country: countryNode});
```

**Comment by skywarth** [comment]
Well that's a simple yet effective solution, it worked well for my case. Much obliged.

By the way thank you for this library, I'm rocking it on a project of mine and it is holding up well. It is robust and well documented.
