### ISSUE TITLE
function add nodes

### ISSUE THREAD

**Issue by gerson-ribeiro** [graphology/graphology#493]
It's possible to create a function inside `MultiDirectedGraph` class responsible for persist the nodes and edges recursively unless add One node/edge per time?

This feature grant that every array that I want to insert in the graph, I can simple map this array transposing to the node/edge structure, and then use something like this `graph.addNodes([...nodes], attributesForEveryNode)`. 

It's really sounds like use the same `graph.addNode` inside an foreach, but do it inside forEach every time is taking too much time to load, further if I decide to update my graph data with redux.

I don't know if this solution is the correct, but I'm have to do almost three or more forks to fill nodes/edges fields from this Graph class.

**Comment by Yomguithereal** [comment]
I am really not sure I understand what you want to say.

> It's really sounds like use the same graph.addNode inside an foreach, but do it inside forEach every time is taking too much time to load,

What do you mean by it is taking too much time to load? Note that redux is geared towards immutable data structures. Are you saying that each mutation to the graph triggers some kind of refresh/re-render down the line? If so you need to find a w

**Comment by gerson-ribeiro** [comment]
> What do you mean by it is taking too much time to load? Are you saying that each mutation to the graph triggers some kind of refresh/re-render down the line? If so you need to find a way to trigger atomic editions to your store (I don't know nor use redux sorry, I cannot help you more).

Not exactly, it's because I am loading to much nodes/edges in my application, and when the user change the data applying filters, it makes lag. But ok, I'll see what I can do about it.

> As a rule, graphology does not implement methods working on plural elements (adding multiple nodes, adding multiples edges at once) because JavaScript does not have a unified way to iterate over things (callbacks, for in, for of, iterators etc. it's a mess) and because it does not yield any performance advantage for me to iterate over things for you.

Understood your point of view. My suggestion was not to iterate my array under the class, but add it directly to the graph.
What I want to suggest is to unless i have to do an for each to fill _nodes field of the class Graph, why I couldn't assign my node array with Graph class _node (obviously this _nodes is private by now), but if we made a `set` function for it?

Think about it, please!
Thank you anyway!

**Comment by Yomguithereal** [comment]
> Not exactly, it's because I am loading to much nodes/edges in my application, and when the user change the data applying filters, it makes lag. But ok, I'll see what I can do about it.

It would not be different if you were populating the keys of an object or a Map, would it?

> My suggestion was not to iterate my array under the class, but add it directly to the graph.

I don't understand what you mean.

> What I want to suggest is to unless i have to do an for each to fill _nodes field of the class Graph, why I couldn't assign my node array with Graph class _node (obviously this _nodes is private by now), but if we made a set function for it?

I don't understand what you mean either.

Let's take your example: `graph.addNodes([...nodes], attributesForEveryNode)`, I would implement this under the hood as: 

```js
nodes.forEach(node => graph.addNode(node, Object.assign({}, attributesForEveryNode));
```

how would this be more performant that what you are already doing?

**Comment by gerson-ribeiro** [comment]
This way you said is not more performant, but if you create a new function graph.addNodes, it will be. Take a look into this file:
https://github.com/graphology/graphology/blob/f918a77581cd5528dbcc07416e09528c4ca6656c/src/graphology/src/graph.js#L124

Here you have `graph._nodes.hasNode(node)`, same way we can implement that `graph._nodes` receive an array directly. I'll take your example:
When I do this:
> graph.addNodes([...nodes], attributesForEveryNode)

 You will be doing `graph._nodes = nodes` under the hood.
 
 Is there anyway to do it?

**Comment by Yomguithereal** [comment]
> You will be doing graph._nodes = nodes under the hood.

This does not make sense. `graph._nodes` is a `Map`, not an array. And this map is interconnected to the `_edges` one through internal indices register. This is what makes the graph invariant holds. When adding a bunch of nodes you always have to check whether they already exist or not (note that asking this is `O(1)` anyway), if you don't you will break the graph's internal structure.

**Comment by gerson-ribeiro** [comment]
Understood your point of view. 
Sorry for taking your time!

Thank you anyway!
