### ISSUE TITLE
[gexf] Support gexf version 1.3

### ISSUE THREAD

**Issue by NitnerocL** [graphology/graphology#496]
Currently, `graphology-gexf` works with GEXF 1.2. Since march 2022, version 1.3 of the specification has been released and is now the prefered version. 
It would be good to update both the parser and the writer to use this new version.

**Comment by Yomguithereal** [comment]
@NitnerocL which [features](https://github.com/gephi/gexf#13) of 1.3 would you require specifically? I ask because dynamics are currently not supported neither by the parser nor the writer currently and some portion of the specs are very costly to implement but used by no one (yet).

**Comment by NitnerocL** [comment]
I'm not using dynamics either and I'm mostly interested in parsing the new `listinteger` attribute type. 
Also I imagine that updating the writer wouldn't require a lot of work, beside changing the xmlns to 1.3?

**Comment by Yomguithereal** [comment]
Ok, let me see what I can do easily. Regarding the writer, I am not sure I want to emit 1.3 by default because I remember some parsers in other languages being very pedantic about this and they might not want to parse a file even if they actually can. I can however add a writer option if you want to specifiy which version you want to emit in the xmlns.

**Comment by NitnerocL** [comment]
I use the JSON-like syntax, as described by the 1.3 specs.

To give a little more context, my team and I recently chose to use a standard format to exchange graph data between our server and our client editor (relying on graphology), and we selected GEXF as such. As we never used it before, we don't have any backward compatibility issue, so we want to stick to the latest version of the specs as much as possible to leverage a truely universal, standard format.

**Comment by Yomguithereal** [comment]
> As we never used it before, we don't have any backward compatibility issue, so we want to stick to the latest version of the specs as much as possible to leverage a truely universal, standard format.

One could cheekily argue that there is no such thing, graph being quite complex objects, but I see your point :)

Let me see what I can do to support the things you need in the following weeks.

**Comment by Yomguithereal** [comment]
- [ ] version option for writer
- [ ] pedantic option for writer
- [ ] hex color support
- [ ] new list attribute parser

**Comment by Yomguithereal** [comment]
@NitnerocL v0.12.0 of `graphology-gexf` was just released. Can you tell me if it fits the bill for you? Note that the parser will understand 1.3 out of the box without needing to tell him to. However the writer still emits 1.2 by default for the time being and you need to explicitly ask to emit 1.3 using the new `version` option. You can also use the writer `pedantic` option for now to avoid xsd validation issues until the issue on the spec is resolved (or not).

**Comment by NitnerocL** [comment]
Everything looks good to me: 1.3 new features are now available, without introducing breaking changes. 
For completeness, maybe you could add `char` and `listchar` types? I don't know how they are represented in xml though. Using single/double quotes? Numeric value? Not that I need any of these anyway.

Thanks again!
