### ISSUE TITLE
[gexf] The generated document doesn't comply with xsd

### ISSUE THREAD

**Issue by NitnerocL** [graphology/graphology#497]
GEXF writer converts graph attributes to children elements of the `<meta>` tag. This results in an invalid gexf file, since this element is meant to only contain `creator`, `description` and `keywords` children.

I'm not sure if there is a better way to do it though, apart from losing the information.

**Comment by NitnerocL** [comment]
I'm not using the writer for now anyway, I just thought it was worth reporting it as an inconsistency. Let's wait and see what gefx's authors think about it, hopefully they will amend the xsd to make it more permissive.

**Comment by Yomguithereal** [comment]
The `pedantic` option was added to the gexf writer for the time being.
