### ISSUE TITLE
Aggregate graphs

### ISSUE THREAD

**Issue by javieralaminos** [graphology/graphology#503]
Hello!

Is there a way of aggregate a graph using an attribute? For example I have a graph of 5 nodes with the color attribute, and a want a new graph with the nodes of the same attributes as a single node, adding all the edges of this nodes. 

Thanks a lot!

**Comment by javieralaminos** [comment]
I mean having a new graph, with only one node per color, aggregating the edges of the origin nodes. I think an example here works better:

Node A, color green, edges A->B and A->C
Node B, color green, edges B-> D
Node C, color blue, edges C->A
Node D, color black, edges D->C
Node E, color black, edges E->C

Resulting graph aggregating by color

Node green, edges green->blue (From A->C), green->black (From B->D). A->B removed
Node blue, edges blue->green (From C->A)
Node black, edges black->blue (From D->C and E->C)

**Comment by Yomguithereal** [comment]
Ok, I see. What you want is usually named an induced graph. I have a function for this in `graphology-operators` but it is not ready yet. For now, you can easily do it without any helper in fact, with something like this:

```js
const colorGraph = new Graph();

graph.forEachNode((node, attr) => {
  colorGraph.mergeNode(attr.color);
  
  graph.forEachNeighbor(node, neighbor => {
    // Filtering out self loops
    if (attr.color === neighbor.color) return;
    colorGraph.mergeEdge(attr.color, neighbor.color);
  });
});
```

I of course assumed an undirected graph in this example, and no particular attributes to report but feel free to adapt to your actual use-case.

**Comment by javieralaminos** [comment]
Thanks a lot!
