### ISSUE TITLE
Release latest version of graphology-library to CDN

### ISSUE THREAD

**Issue by longmtran** [graphology/graphology#510]
Hi,

Is there any plan to release the latest version to npm or plan to have the assets in /dist/ folder in github so that it can be served by jsdelivr?

The current version on npm is quite out of date 0.8.0, served by jsdelivr cdn: https://www.jsdelivr.com/package/npm/graphology-library.

Thanks.

**Comment by Yomguithereal** [comment]
`0.8.0` is the latest version of `graphology-library`.
