### ISSUE TITLE
directedEdges Returns Both Forward and Reverse Edges in DirectedGraph

### ISSUE THREAD

**Issue by hljie** [graphology/graphology#522]
I am experiencing an problem with the directedEdges method in the DirectedGraph class of the graphology. According to the documentation：`Using source & target: will iterate over the relevant edges going from source to target`. However, in my implementation, it returns both the edges from source to target as well as from target to source.

example code:
`function test() {
    const graph = new graphology.DirectedGraph();

    graph.addNode('a');
    graph.addNode('b');
    graph.addEdge('a', 'b', { label: 'a to b' });
    graph.addEdge('b', 'a', { label: 'b to a' });

    const edges = graph.directedEdges('a', 'b');
    console.log('Edges from a to b:', edges.map(id => graph.getEdgeAttributes(id)));

}`

I get the result:
`Edges from a to b: [ { label: 'b to a' }, { label: 'a to b' } ]`

the `{ label: 'b to a' }` should not be returned

**Comment by Yomguithereal** [comment]
I agree the documentation could be clearer sometimes, but the behavior of `#.directedEdges` you demonstrate here is correct. You are confusing it with `#.outEdges` or `#.inEdges`. `#.directedEdges` is typically used with mixed graphs to discriminate between directed and undirected edges, so in a directed graph `#.directedEdges` is functionally identical to `#.edges`.
