### ISSUE TITLE
Better typing for AttributeUpdatePayload

### ISSUE THREAD

**Issue by NitnerocL** [graphology/graphology#527]
Hi!

The `name` property of of `AttributeUpdatePayload<ItemAttributes>` is merely typed as `string`. Shouldn't it be of type `keyof ItemAttributes`?

**Comment by Yomguithereal** [comment]
You are right indeed. I have updated the types. It is published as `graphology-types@0.24.8`

**Comment by NitnerocL** [comment]
Thanks!
