### ISSUE TITLE
Method to "updgrade" a simple graph to a multi one

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#82]
@jacomyma I am tinkering with the idea of adding a method to the graph permitting to "upgrade" a simple graph to a "multi" graph (possible trivially from simple to multi & very efficiently but not the other way around).

This would enable use cases such as the one we discussed this morning concerning gexf and a way to still be able to stream data from the XML file server-side.

So, do you think this is a good idea and what name would you give to such a method? I struggle to find something vaguely coherent.

```js
graph.convertToMulti();
```

**Comment by jacomyma** [comment]
"convert" seems alright! I can imagine it also applies to other cases like multi to simple, directed to undirected and vice-versa... with loss of course but I can see that being useful nevertheless.
